source 'https://rubygems.org'
ruby '2.3.1'

gem 'jekyll'
gem 'jekyll-paginate'
gem 'jekyll-responsive_image', '0.17.0'
gem 'rake'
gem 'html-proofer'
gem 'jekyll-archives'
gem 'octopress-autoprefixer'
